### PR TITLE
Create Immanuel's skeletal PPP and update AboutUs

### LINKED ISSUE #23: [Immanuel] Create skeletal PPP and Update AboutUs.md
- Add skeletal PPP
- Update AboutUs.md to link to PPP created
- Simulatneously update AboutUs.md roles and responsibilities

### PR DESCRIPTION
**Pull request by HEEaZ**
Closes #23

### CODE REVIEW

**Review by LinWanLeii — APPROVED** [review]
LGTM

**Review by timetraveller-123 — APPROVED** [review]
LGTM

**Review by timetraveller-123 — CHANGES_REQUESTED** [review]
Perhaps could change name of PPP to lower case github username to match project requirements.

**Review by timetraveller-123 — APPROVED** [review]
LGTM

**Review by joeng03 — APPROVED** [review]

**Pull request merged**
